[book]
authors = ["Calascibetta Romain"]
language = "en"
multilingual = false
src = "src"
title = "MirageVPN - a VPN as an unikernel"

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false
